### ISSUE TITLE
Output only the relevant information that is not in the physical parameters and orbits file

### ISSUE THREAD

**Issue by mschwamb** [dirac-institute/survey_simulator_post_processing#102]
To start:

ObjID   FieldMJD         AstRA(deg)   AstDec(deg)    MagnitudeInFilter   optFilter   fieldRA fieldDec    fiveSigmaDepth   - should be what is object for each detection. 

User has the other information in the OIF output so they could recreate other columns needed. 

Future discussions can be about what additional information the user should want where we could set up a config file variable, but with databases and pandas , it is a trivial task to combine a query to get orbit, colors, etc. that this information should not be duplicated in the output

**Comment by mschwamb** [comment]
Things above have changed, but this is something that would be good to get done before the sprint

**Comment by astronomerritt** [comment]
In Slack [a while back](https://qubsolarsystem.slack.com/archives/CQYN0CN00/p1647352485150209?thread_ts=1647350994.809689&cid=CQYN0CN00) the desired output was listed as 

`ObjID  FieldMJD  AstRA(deg)  AstDec(deg) MagnitudeInFilter optFilter  fieldRA fieldDec fiveSigmaDepth`

MagnitudeInFilter no longer exists. My guess would be that 'observedTrailedSourceMag' is the one we want to output, can anyone confirm?

Also, do we want fiveSigmaDepthAtSource instead of fiveSigmaDepth?

**Comment by astronomerritt** [comment]
Also also (sorry), do we want to include a config file flag for the full output if the user really wants it?

**Comment by fedorets** [comment]
I think PSFApparentMagnitude would be the correct one since that is the one that is measured. The difference between the TrailedSourceMag is, as the name suggests, trailing loss. Since I can imagine a case where both are needed, I would select the PSF as the primary output, and the TrailedSourceMag as an option.

Similarly for the fiveSigmaDepths, the "atSource" one is I imagine the one without vignetting, and the measured one is the plain one. Again, I think the measured one should be the primary option, with the AtSource one as an option.

So this brings me to your final question, about full output. I see there are a lot of different options that may be required, but it is probably not worth going through them individually in the config file. So for those of us who would like to dig through the specifics I think the correct way is to dump everything in the full output and then search for what is needed. So yes, I am strongly in support of the full output option.

**Comment by astronomerritt** [comment]
Got it, that makes sense. I'm not seeing anything called PSFApparentMagnitude in the output -- I assume this is observedPSFMag? I just went through the code again to remind myself of what every column is and where it comes from and I think I have a better grasp of it now...

Currently I'm thinking of having just two options for output: a default which is just the necessary columns, and then an option to output everything.

**Comment by mschwamb** [comment]
Everything in the input files should not be ouputted for the user even if as secondary option.  If the user cannot figure out how to read in their own files that is their own issue. Making a bloated out file is not good for maintenance .

**Comment by mschwamb** [comment]
object_id, trailed source_mag, psf_mag, field ID, mjd of detection, position of the object (RA and DEC), and all associated uncertainties, and observation filter should be outputted.

**Comment by astronomerritt** [comment]
Okay, will do. 

I've already written functionality to change the output based on user selection. I can remove it all again, or I can leave the code in with a single option (outputting only the columns you've defined) in case we do want to use it later.

**Comment by mschwamb** [comment]
A few more things I forgot, 5 sigma limiting magnitude at the source

**Comment by mschwamb** [comment]
We should not be doing output based on user selection that makes it very easy for the user to screw up and output the wrong magnitude and do the wrong thing.

**Comment by mschwamb** [comment]
I don't care how the implementation is done, but let's not make it easy for the user to change it (ie no config file variable where the user specify the columns)

**Comment by mschwamb** [comment]
We can give some preset options like an advanced option that can have more information and talk to the folks of the sprint for what that info should

**Comment by astronomerritt** [comment]
Yeah, I was definitely thinking 'preset options': basically, I have written it now so there is only one option for output, which is 'default', which outputs _only_ the columns you've listed. 

Then, if folks want an 'advanced' output we can easily add that down the line.

The columns I have are: 

`'ObjID', 'FieldMJD', 'fieldRA', 'fieldDec', 'AstRA(deg)', 'AstDec(deg)', 'AstrometricSigma(deg)', 'optFilter', 'observedPSFMag', 'observedTrailedSourceMag', 'PhotometricSigma(mag)', 'fiveSigmaDepth', 'fiveSigmaDepthAtSource', 'SNR'`

Does that seem okay?

**Comment by mschwamb** [comment]
|observedPSFMag and observedTrailedSourceMag should both have their own 
uncertainties. If not talk to Sam about that.
|

|I would leave SNR for the advanced option.
|

**Comment by astronomerritt** [comment]
Currently observedPSFMag and observedTrailedSourceMag do not have their own uncertainties, and _PPRandomizeMeasurements_ uses "PhotometricSigma(mag)" for both. 

I can message Sam on Slack about it, but I think I see how to fix this myself. 

Essentially, in _PPAddUncertainties.addUncertainties,_ there should be two calls to _uncertainties_: one for the trailed source magnitude, and one for the PSF magntitude, to generate their own versions of PhotometricSigma(mag). Could be called something like "PhotometricSigmaPSF(mag)" and "PhotometricSigmaTrailedSource(mag)".

**Comment by mschwamb** [comment]
It calculates some SNR too so I think one has to be careful about that

**Comment by astronomerritt** [comment]
I can save both versions of the SNR with different names (making sure the code calls on the right one moving forward), or just the SNR for PSFMag (which is the relevant one). The SNR only seems to be used for making cuts based on SNR, although if I'm wrong on this I'll find out when I test it.

Could also fix #211 while I'm in there. Might be quicker if I do this myself, I can definitely have it done today. :) But happy to consult Sam if you prefer.

**Comment by mschwamb** [comment]
consult sam and just use the one SNR for now.

**Comment by astronomerritt** [comment]
On it.
