### ISSUE TITLE
Add survey flag to command line/check to see if specified filter is in survey

### ISSUE THREAD

**Issue by astronomerritt** [dirac-institute/survey_simulator_post_processing#71]
In the future, it might be nice if this could be used with other surveys, so we can signal that possibility now and make it easier in the future. The plan is to add a survey flag to the command line for which the default is "lsst". In the future, functionality for other surveys could then be added.

I also then want to add a check so that if a filter is given in the config file that isn't one of the LSST filters, the program exits gracefully.

- [ ] add survey flag to command line arguments
- [ ] check to see if requested filters are actually LSST filters

**Comment by mschwamb** [comment]
for  add survey flag to command line arguments, I think we should rename runPostProcessing(parser) to runLSSTPostProcessing (parser) or whatever the appropriate version of that under proper function naming and have the if statement in the main so that's where the change to another survey would happen.

**Comment by mschwamb** [comment]
@astronomerritt would it be possible to tackle this one today?

**Comment by mschwamb** [comment]
It would be a good one to have done for the call

**Comment by mschwamb** [comment]
u,g,r,i,z are the accepted LSST filters

**Comment by astronomerritt** [comment]
> @astronomerritt would it be possible to tackle this one today?

No problem, shouldn't take long.
